spring.application.name=ss07-validate
server.port=8888
# C?u hình k?t n?i PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/bt6?currentSchema=demo
spring.datasource.username=postgres
spring.datasource.password=123456$
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
